jobs:
  - job: terraform_extension
    steps: 
    - task: DownloadPipelineArtifact@2
      displayName: download terraform extension
      inputs: 
        artifact: terraform_extension
        path: $(terraform_extension_dir)
    - task: Npm@1
      displayName: install  
      inputs:
        workingDir: $(terraform_extension_dir)
        command: install
    - task: Npm@1
      displayName: install extension
      continueOnError: 'true'
      inputs:
        workingDir: ${{ parameters.directory }}
        command: custom
        customCommand: run install:extension -- -t $(ado_access_token) -u $(ado_service_url)